baseURL = 'https://wehumanists.org/'
locale = 'en-us'
title = 'We Humanists'
theme = 'paper'
enableGitInfo = true

[module.hugoVersion]
  extended = true
  min = '0.158.0'

[params]
  description = 'Humans for Humanism and Progress'

[frontmatter]
  date = ['date', 'publishDate', 'lastmod']
  expiryDate = ['expiryDate']
  lastmod = [':git', 'lastmod', 'date', 'publishDate']
  publishDate = ['publishDate', 'date']

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10
